//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB_Guadalupana.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcredito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string buscarcredito(string variablebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcredito", ReplyAction="*")]
        System.Threading.Tasks.Task<string> buscarcreditoAsync(string variablebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarresponsables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarresponsables(string variabledebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarresponsables", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarresponsablesAsync(string variabledebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcreditosasociados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarcreditosasociados(string valordebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcreditosasociados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarcreditosasociadosAsync(string valordebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcreditoporcif", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarcreditoporcif(string valordebusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcreditoporcif", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarcreditoporcifAsync(string valordebusqueda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : KB_Guadalupana.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<KB_Guadalupana.ServiceReference1.WebService1Soap>, KB_Guadalupana.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string buscarcredito(string variablebusqueda) {
            return base.Channel.buscarcredito(variablebusqueda);
        }
        
        public System.Threading.Tasks.Task<string> buscarcreditoAsync(string variablebusqueda) {
            return base.Channel.buscarcreditoAsync(variablebusqueda);
        }
        
        public System.Data.DataSet buscarresponsables(string variabledebusqueda) {
            return base.Channel.buscarresponsables(variabledebusqueda);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarresponsablesAsync(string variabledebusqueda) {
            return base.Channel.buscarresponsablesAsync(variabledebusqueda);
        }
        
        public System.Data.DataSet buscarcreditosasociados(string valordebusqueda) {
            return base.Channel.buscarcreditosasociados(valordebusqueda);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarcreditosasociadosAsync(string valordebusqueda) {
            return base.Channel.buscarcreditosasociadosAsync(valordebusqueda);
        }
        
        public System.Data.DataSet buscarcreditoporcif(string valordebusqueda) {
            return base.Channel.buscarcreditoporcif(valordebusqueda);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarcreditoporcifAsync(string valordebusqueda) {
            return base.Channel.buscarcreditoporcifAsync(valordebusqueda);
        }
    }
}
